import { query } from '../db.js';
import { resolveSeedWorkspace } from './resolveSeedWorkspace.js';

async function seedGovernanceData() {
  console.log('Seeding Governance Documents and Review Tasks...');
  const workspace = await resolveSeedWorkspace();
  const workspaceId = workspace.id;

  // Seed Governance Documents
  const documents = [
    {
      id: 'GD-001',
      workspace_id: workspaceId,
      title: 'Information Security Policy',
      description: 'Enterprise policy defining baseline information security objectives, governance, and responsibilities.',
      doc_type: 'policy',
      owner: 'Alice Johnson',
      status: 'active',
      classification: 'internal',
      current_version: '3.0',
      location_url: 'https://sharepoint.company.com/policies/info-security-policy.pdf',
      review_frequency_months: 12,
      next_review_date: '2025-03-15',
      last_reviewed_at: '2024-03-15',
      published_at: '2024-03-20T09:00:00Z',
      effective_date: '2024-04-01',
      attestation_required: true,
      file_name: 'information-security-policy-v3.0.pdf',
      file_size_bytes: 482000,
      mime_type: 'application/pdf',
    },
    {
      id: 'GD-002',
      workspace_id: workspaceId,
      title: 'Data Classification Standard',
      description: 'Classification and handling requirements for corporate and regulated data sets.',
      doc_type: 'standard',
      owner: 'Bob Smith',
      status: 'published',
      classification: 'internal',
      current_version: '2.1',
      location_url: 'https://sharepoint.company.com/standards/data-classification.pdf',
      review_frequency_months: 12,
      next_review_date: '2025-02-01',
      last_reviewed_at: '2024-02-01',
      published_at: '2024-02-05T08:00:00Z',
      effective_date: '2024-02-12',
      file_name: 'data-classification-standard-v2.1.pdf',
      file_size_bytes: 318000,
      mime_type: 'application/pdf',
    },
    {
      id: 'GD-003',
      workspace_id: workspaceId,
      title: 'Incident Response Procedure',
      description: 'Operational response procedure for triage, containment, communications, and escalation.',
      doc_type: 'procedure',
      owner: 'Carol Davis',
      status: 'active',
      classification: 'confidential',
      current_version: '1.5',
      location_url: 'https://sharepoint.company.com/procedures/incident-response.pdf',
      review_frequency_months: 6,
      next_review_date: '2025-06-01',
      last_reviewed_at: '2024-12-01',
      effective_date: '2024-12-15',
      file_name: 'incident-response-procedure-v1.5.pdf',
      file_size_bytes: 265000,
      mime_type: 'application/pdf',
    },
    {
      id: 'GD-004',
      workspace_id: workspaceId,
      title: 'Access Control Policy',
      description: 'Policy covering access provisioning, periodic access review, and privileged access control.',
      doc_type: 'policy',
      owner: 'David Lee',
      status: 'under_review',
      classification: 'internal',
      current_version: '2.0',
      location_url: 'https://sharepoint.company.com/policies/access-control.pdf',
      review_frequency_months: 12,
      next_review_date: '2025-01-30',
      last_reviewed_at: '2024-01-30',
      attestation_required: true,
    },
    {
      id: 'GD-005',
      workspace_id: workspaceId,
      title: 'Acceptable Use Policy',
      description: 'Defines acceptable use obligations for workforce users, contractors, and third parties.',
      doc_type: 'policy',
      owner: 'Eve Martinez',
      status: 'pending_attestation',
      classification: 'internal',
      current_version: '4.0',
      location_url: 'https://sharepoint.company.com/policies/acceptable-use.pdf',
      review_frequency_months: 12,
      next_review_date: '2025-07-01',
      last_reviewed_at: '2024-07-01',
      published_at: '2024-07-05T12:00:00Z',
      effective_date: '2024-07-12',
      attestation_required: true,
    },
    {
      id: 'GD-006',
      workspace_id: workspaceId,
      title: 'Password Management Guideline',
      description: 'User-facing guidance for password hygiene, vault usage, and MFA expectations.',
      doc_type: 'guideline',
      owner: 'Frank Wilson',
      status: 'draft',
      classification: 'internal',
      current_version: '1.0',
      location_url: null,
      review_frequency_months: 12,
      next_review_date: '2026-01-01',
      last_reviewed_at: null,
    },
    {
      id: 'GD-007',
      workspace_id: workspaceId,
      title: 'Privacy Policy',
      description: 'Privacy governance policy aligned to GDPR, HIPAA, and data subject rights obligations.',
      doc_type: 'policy',
      owner: 'Grace Brown',
      status: 'active',
      classification: 'internal',
      current_version: '2.5',
      location_url: 'https://sharepoint.company.com/policies/privacy-policy.pdf',
      review_frequency_months: 12,
      next_review_date: '2025-04-15',
      last_reviewed_at: '2024-04-15',
      effective_date: '2024-05-01',
      published_at: '2024-04-20T15:00:00Z',
    },
    {
      id: 'GD-008',
      workspace_id: workspaceId,
      title: 'Business Continuity Management Framework',
      description: 'Framework document defining resilience governance, testing cadence, and recovery oversight.',
      doc_type: 'framework_document',
      owner: 'Henry Taylor',
      status: 'published',
      classification: 'restricted',
      current_version: '1.2',
      location_url: 'https://sharepoint.company.com/manuals/bc-manual.pdf',
      review_frequency_months: 24,
      next_review_date: '2026-06-01',
      last_reviewed_at: '2024-06-01',
      published_at: '2024-06-10T10:30:00Z',
      effective_date: '2024-06-15',
    },
    {
      id: 'GD-009',
      workspace_id: workspaceId,
      title: 'Control Exception Register',
      description: 'Compliance register tracking approved control exceptions, owners, expiry, and remediation follow-up.',
      doc_type: 'compliance_register',
      owner: 'Ivy Clark',
      status: 'active',
      classification: 'confidential',
      current_version: '3.1',
      location_url: 'https://sharepoint.company.com/procedures/change-management.pdf',
      review_frequency_months: 6,
      next_review_date: '2025-05-01',
      last_reviewed_at: '2024-11-01',
      effective_date: '2024-11-05',
    },
    {
      id: 'GD-010',
      workspace_id: workspaceId,
      title: 'Third-Party Risk Standard',
      description: 'Superseded vendor risk standard retained for historical and audit purposes.',
      doc_type: 'vendor_document',
      owner: 'Jack Anderson',
      status: 'superseded',
      classification: 'internal',
      current_version: '1.0',
      location_url: 'https://sharepoint.company.com/archive/vendor-mgmt-v1.pdf',
      review_frequency_months: null,
      next_review_date: null,
      last_reviewed_at: '2023-01-15',
      archived_at: '2023-01-16T09:00:00Z',
      file_name: 'third-party-risk-standard-v1.pdf',
      file_size_bytes: 221000,
      mime_type: 'application/pdf',
    },
    {
      id: 'GD-011',
      workspace_id: workspaceId,
      title: 'Audit Evidence Submission Guidance',
      description: 'Guidance for control owners submitting evidence in support of internal and external audits.',
      doc_type: 'evidence_document',
      owner: 'Lena Okafor',
      status: 'active',
      classification: 'internal',
      current_version: '1.1',
      location_url: 'https://sharepoint.company.com/guidance/audit-evidence-submission.pdf',
      review_frequency_months: 12,
      next_review_date: '2025-09-01',
      last_reviewed_at: '2024-09-01',
      effective_date: '2024-09-05',
      file_name: 'audit-evidence-submission-guidance-v1.1.pdf',
      file_size_bytes: 176000,
      mime_type: 'application/pdf',
    },
    {
      id: 'GD-012',
      workspace_id: workspaceId,
      title: 'Management Review Minutes - Q2',
      description: 'Management review document capturing strategic compliance decisions, escalations, and action owners.',
      doc_type: 'management_review_document',
      owner: 'Chief Risk Office',
      status: 'archived',
      classification: 'restricted',
      current_version: '1.0',
      location_url: 'https://sharepoint.company.com/reviews/management-review-q2.pdf',
      review_frequency_months: 3,
      next_review_date: '2025-10-01',
      last_reviewed_at: '2025-07-01',
      published_at: '2025-07-02T13:00:00Z',
      effective_date: '2025-07-02',
      archived_at: '2025-07-02T18:00:00Z',
    },
  ];

  for (const doc of documents) {
    await query(
      `INSERT INTO governance_documents (
        id, workspace_id, title, description, doc_type, owner, status, classification, current_version,
        location_url, review_frequency_months, next_review_date, last_reviewed_at,
        published_at, effective_date, expiry_date, archived_at, superseded_by_id,
        attestation_required, file_name, file_size_bytes, mime_type
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13,
        $14, $15, $16, $17, $18,
        $19, $20, $21, $22
      )
      ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        doc_type = EXCLUDED.doc_type,
        owner = EXCLUDED.owner,
        status = EXCLUDED.status,
        classification = EXCLUDED.classification,
        current_version = EXCLUDED.current_version,
        location_url = EXCLUDED.location_url,
        review_frequency_months = EXCLUDED.review_frequency_months,
        next_review_date = EXCLUDED.next_review_date,
        last_reviewed_at = EXCLUDED.last_reviewed_at,
        published_at = EXCLUDED.published_at,
        effective_date = EXCLUDED.effective_date,
        expiry_date = EXCLUDED.expiry_date,
        archived_at = EXCLUDED.archived_at,
        superseded_by_id = EXCLUDED.superseded_by_id,
        attestation_required = EXCLUDED.attestation_required,
        file_name = EXCLUDED.file_name,
        file_size_bytes = EXCLUDED.file_size_bytes,
        mime_type = EXCLUDED.mime_type,
        updated_at = NOW()`,
      [
        doc.id,
        doc.workspace_id,
        doc.title,
        (doc as any).description || null,
        doc.doc_type,
        doc.owner,
        doc.status,
        (doc as any).classification || null,
        doc.current_version || null,
        doc.location_url || null,
        doc.review_frequency_months || null,
        doc.next_review_date || null,
        doc.last_reviewed_at || null,
        (doc as any).published_at || null,
        (doc as any).effective_date || null,
        (doc as any).expiry_date || null,
        (doc as any).archived_at || null,
        (doc as any).superseded_by_id || null,
        (doc as any).attestation_required || false,
        (doc as any).file_name || null,
        (doc as any).file_size_bytes || null,
        (doc as any).mime_type || null,
      ]
    );
  }
  console.log(`  ✓ Seeded ${documents.length} governance documents`);

  // Seed Review Tasks
  const tasks = [
    {
      id: 'RT-001',
      workspace_id: workspaceId,
      document_id: 'GD-001',
      title: 'Annual Review: Information Security Policy',
      description: 'Conduct annual review of the Information Security Policy to ensure alignment with current threats and business needs.',
      assignee: 'Alice Johnson',
      assignee_email: 'alice.johnson@company.com',
      status: 'open',
      due_at: '2025-03-15',
      reminder_days_before: [30, 7, 1],
    },
    {
      id: 'RT-002',
      workspace_id: workspaceId,
      document_id: 'GD-002',
      title: 'Annual Review: Data Classification Standard',
      description: 'Review and update data classification levels and handling procedures.',
      assignee: 'Bob Smith',
      assignee_email: 'bob.smith@company.com',
      status: 'in_progress',
      due_at: '2025-02-01',
      reminder_days_before: [30, 7, 1],
    },
    {
      id: 'RT-003',
      workspace_id: workspaceId,
      document_id: 'GD-004',
      title: 'Annual Review: Access Control Policy',
      description: 'Review access control requirements and update based on recent audit findings.',
      assignee: 'David Lee',
      assignee_email: 'david.lee@company.com',
      status: 'overdue',
      due_at: '2025-01-30',
      reminder_days_before: [30, 7, 1],
    },
    {
      id: 'RT-004',
      workspace_id: workspaceId,
      document_id: 'GD-003',
      title: 'Semi-Annual Review: Incident Response Procedure',
      description: 'Review and update incident response procedures based on lessons learned.',
      assignee: 'Carol Davis',
      assignee_email: 'carol.davis@company.com',
      status: 'open',
      due_at: '2025-06-01',
      reminder_days_before: [30, 14, 7, 1],
    },
    {
      id: 'RT-005',
      workspace_id: workspaceId,
      document_id: 'GD-007',
      title: 'Annual Review: Privacy Policy',
      description: 'Review privacy policy for compliance with GDPR and CCPA requirements.',
      assignee: 'Grace Brown',
      assignee_email: 'grace.brown@company.com',
      status: 'open',
      due_at: '2025-04-15',
      reminder_days_before: [30, 7, 1],
    },
    {
      id: 'RT-006',
      workspace_id: workspaceId,
      document_id: 'GD-009',
      title: 'Semi-Annual Review: Change Management Procedure',
      description: 'Review change management process for efficiency and compliance.',
      assignee: 'Ivy Clark',
      assignee_email: 'ivy.clark@company.com',
      status: 'open',
      due_at: '2025-05-01',
      reminder_days_before: [14, 7, 1],
    },
    {
      id: 'RT-007',
      workspace_id: workspaceId,
      document_id: 'GD-005',
      title: 'Completed: Acceptable Use Policy Review',
      description: 'Annual review completed with minor updates.',
      assignee: 'Eve Martinez',
      assignee_email: 'eve.martinez@company.com',
      status: 'completed',
      due_at: '2024-07-01',
      completed_at: '2024-06-28',
      reminder_days_before: [30, 7, 1],
    },
    {
      id: 'RT-008',
      workspace_id: workspaceId,
      document_id: 'GD-008',
      title: 'Biennial Review: Business Continuity Manual',
      description: 'Comprehensive review of BCP manual and testing procedures.',
      assignee: 'Henry Taylor',
      assignee_email: 'henry.taylor@company.com',
      status: 'open',
      due_at: '2026-06-01',
      reminder_days_before: [60, 30, 14, 7, 1],
    },
  ];

  for (const task of tasks) {
    await query(
      `INSERT INTO review_tasks (
        id, workspace_id, document_id, title, description, assignee, assignee_email, status,
        due_at, reminder_days_before, completed_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
      ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        assignee = EXCLUDED.assignee,
        assignee_email = EXCLUDED.assignee_email,
        status = EXCLUDED.status,
        due_at = EXCLUDED.due_at,
        reminder_days_before = EXCLUDED.reminder_days_before,
        completed_at = EXCLUDED.completed_at,
        updated_at = NOW()`,
      [
        task.id,
        task.workspace_id,
        task.document_id,
        task.title,
        task.description || null,
        task.assignee,
        (task as any).assignee_email || null,
        task.status,
        task.due_at,
        task.reminder_days_before,
        (task as any).completed_at || null,
      ]
    );
  }
  console.log(`  ✓ Seeded ${tasks.length} review tasks`);

  // Seed Document Review Logs (for completed tasks)
  const reviewLogs = [
    {
      id: 'DRL-001',
      workspace_id: workspaceId,
      document_id: 'GD-005',
      review_task_id: 'RT-007',
      reviewed_by: 'Eve Martinez',
      reviewed_at: '2024-06-28T14:30:00Z',
      decision: 'no_change',
      comments: 'Policy reviewed and found to be current. No changes required.',
    },
    {
      id: 'DRL-002',
      workspace_id: workspaceId,
      document_id: 'GD-001',
      review_task_id: null,
      reviewed_by: 'Alice Johnson',
      reviewed_at: '2024-03-15T10:00:00Z',
      decision: 'update_required',
      comments: 'Updated to version 3.0 with new cloud security requirements.',
      new_version: '3.0',
    },
    {
      id: 'DRL-003',
      workspace_id: workspaceId,
      document_id: 'GD-010',
      review_task_id: null,
      reviewed_by: 'Jack Anderson',
      reviewed_at: '2023-01-15T09:00:00Z',
      decision: 'retire',
      comments: 'Superseded by new Third-Party Risk Management Policy.',
    },
  ];

  for (const log of reviewLogs) {
    // Skip logs that reference tasks - the FK constraint may fail if task doesn't exist
    if (log.review_task_id) {
      await query(
        `INSERT INTO document_review_logs (
          id, workspace_id, document_id, review_task_id, reviewed_by, reviewed_at,
          decision, comments, new_version
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        ON CONFLICT (id) DO UPDATE SET
          decision = EXCLUDED.decision,
          comments = EXCLUDED.comments,
          new_version = EXCLUDED.new_version`,
        [
          log.id,
          log.workspace_id,
          log.document_id,
          log.review_task_id,
          log.reviewed_by,
          log.reviewed_at,
          log.decision,
          log.comments || null,
          log.new_version || null,
        ]
      );
    }
  }
  console.log(`  ✓ Seeded document review logs`);

  console.log('Governance data seeding complete!');
}

seedGovernanceData()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('Seeding failed:', err);
    process.exit(1);
  });
