[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh -lc \"npm run seed:core && npm run start\""
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
