import { randomUUID } from 'node:crypto';
import { query } from '../db.js';

export type RiskLibraryStatus = 'draft' | 'active' | 'archived';
export interface RiskLibraryTemplateInput {
  title: string; description?: string; category: string; suggestedOwner?: string | null;
  scenarioType?: 'event_based' | 'asset_based'; riskSource?: string | null; threatEvent?: string | null;
  vulnerability?: string | null; predisposingCondition?: string | null;
  suggestedCiaImpacts?: string[]; commonCauses?: string[]; commonConsequences?: string[];
  suggestedInherentLikelihood?: number | null; suggestedInherentImpact?: number | null;
  likelihoodRationale?: string | null; impactRationale?: string | null;
  suggestedControls?: string[]; suggestedEvidence?: string[]; relatedFrameworks?: string[];
  relatedControlIds?: string[]; treatmentSuggestions?: string[]; monitoringIndicators?: string[];
  tags?: string[]; status?: RiskLibraryStatus;
}
const jsonColumns = new Set(['suggested_cia_impacts','common_causes','common_consequences','suggested_controls','suggested_evidence','related_frameworks','related_control_ids','treatment_suggestions','monitoring_indicators','tags']);
const DEFAULT_LIBRARY_TEMPLATES: RiskLibraryTemplateInput[] = [
  { title:'Ransomware disrupts critical business services', description:'A ransomware event encrypts or disables critical systems and interrupts priority business services.', category:'information_security', scenarioType:'event_based', riskSource:'External threat actor', threatEvent:'Ransomware infection and extortion', vulnerability:'Unpatched systems, weak segmentation, or ineffective recovery controls', predisposingCondition:'Critical services depend on connected technology platforms', suggestedOwner:'Security Office', suggestedCiaImpacts:['Confidentiality','Integrity','Availability'], commonCauses:['Exploited vulnerability','Credential compromise','Malicious attachment'], commonConsequences:['Service interruption','Data loss or disclosure','Recovery cost and regulatory scrutiny'], suggestedInherentLikelihood:4, suggestedInherentImpact:5, suggestedControls:['Vulnerability management','Endpoint protection','Network segmentation','Tested backup and recovery'], suggestedEvidence:['Vulnerability scan results','Endpoint coverage report','Recovery exercise record'], relatedFrameworks:['ISO 27005','NIST SP 800-30'], relatedControlIds:[], treatmentSuggestions:['Mitigate','Transfer'], monitoringIndicators:['Critical vulnerabilities overdue','Endpoint coverage gaps','Recovery test failures'], tags:['cyber','ransomware','resilience'], status:'active' },
  { title:'Privileged access is misused or compromised', description:'Excessive, unmanaged, or compromised privileged access enables unauthorized activity in critical systems.', category:'information_security', scenarioType:'asset_based', riskSource:'Internal or external actor', threatEvent:'Unauthorized privileged activity', vulnerability:'Excessive rights, weak authentication, or incomplete access reviews', predisposingCondition:'Administrative access is required across critical platforms', suggestedOwner:'Identity Security', suggestedCiaImpacts:['Confidentiality','Integrity','Availability'], commonCauses:['Credential theft','Dormant privileged account','Segregation-of-duties conflict'], commonConsequences:['Unauthorized change','Sensitive data exposure','Service disruption'], suggestedInherentLikelihood:4, suggestedInherentImpact:5, suggestedControls:['Privileged access management','Multi-factor authentication','Periodic access review'], suggestedEvidence:['Privileged account inventory','Access review record','Authentication policy'], relatedFrameworks:['ISO 27005','NIST SP 800-30'], relatedControlIds:[], treatmentSuggestions:['Mitigate'], monitoringIndicators:['Privileged accounts not reviewed','Failed privileged logins'], tags:['identity','privileged-access'], status:'active' },
  { title:'Critical third-party service becomes unavailable', description:'A material supplier or technology provider fails to deliver an essential service within agreed recovery expectations.', category:'vendor', scenarioType:'event_based', riskSource:'Critical third party', threatEvent:'Supplier outage or service degradation', vulnerability:'Concentration risk, weak continuity commitments, or limited alternatives', predisposingCondition:'A priority business process depends on an external provider', suggestedOwner:'Third-Party Office', suggestedCiaImpacts:['Availability','Integrity'], commonCauses:['Provider outage','Subcontractor failure','Capacity constraint'], commonConsequences:['Operational disruption','Customer impact','Contractual or financial loss'], suggestedInherentLikelihood:3, suggestedInherentImpact:5, suggestedControls:['Supplier due diligence','Contractual resilience requirements','Exit and continuity planning'], suggestedEvidence:['Supplier assessment','Service report','Business continuity test'], relatedFrameworks:['ISO 27005','NIST SP 800-30'], relatedControlIds:[], treatmentSuggestions:['Mitigate','Transfer','Avoid'], monitoringIndicators:['SLA breaches','Unresolved critical findings','Recovery tests overdue'], tags:['vendor','resilience','concentration'], status:'active' },
  { title:'Personal data is disclosed without authorization', description:'Personal or confidential information is accessed, shared, or exposed contrary to legal, contractual, or policy requirements.', category:'privacy', scenarioType:'asset_based', riskSource:'People, process, technology, or third party', threatEvent:'Unauthorized disclosure of personal data', vulnerability:'Weak access control, handling practices, or data-loss prevention', predisposingCondition:'The organisation processes sensitive personal information', suggestedOwner:'Privacy Office', suggestedCiaImpacts:['Confidentiality','Integrity'], commonCauses:['Misdirected communication','Access control failure','Third-party breach'], commonConsequences:['Regulatory notification','Harm to data subjects','Reputational and financial loss'], suggestedInherentLikelihood:3, suggestedInherentImpact:5, suggestedControls:['Data classification','Least-privilege access','Data loss prevention','Incident response'], suggestedEvidence:['Processing inventory','Access review record','Incident exercise'], relatedFrameworks:['ISO 27005','NIST SP 800-30'], relatedControlIds:[], treatmentSuggestions:['Mitigate','Transfer'], monitoringIndicators:['Privacy incidents','Unresolved data access exceptions'], tags:['privacy','data-protection'], status:'active' },
  { title:'Regulatory obligation is not met by its due date', description:'A legal, regulatory, or contractual obligation is missed or implemented ineffectively.', category:'compliance', scenarioType:'event_based', riskSource:'Regulatory change or control failure', threatEvent:'Non-compliance with a binding obligation', vulnerability:'Incomplete obligation ownership, monitoring, or evidence', predisposingCondition:'The organisation operates within regulated or contractual requirements', suggestedOwner:'Compliance Office', suggestedCiaImpacts:['Integrity'], commonCauses:['Unassigned obligation','Late regulatory change assessment','Insufficient assurance evidence'], commonConsequences:['Enforcement action','Financial penalty','Remediation programme'], suggestedInherentLikelihood:3, suggestedInherentImpact:4, suggestedControls:['Obligation register','Regulatory change process','Compliance monitoring'], suggestedEvidence:['Compliance assessment','Approval record','Control test result'], relatedFrameworks:['ISO 27005','NIST SP 800-30'], relatedControlIds:[], treatmentSuggestions:['Mitigate','Avoid'], monitoringIndicators:['Overdue obligations','Failed compliance tests'], tags:['compliance','regulatory'], status:'active' },
  { title:'Critical process cannot recover within business tolerance', description:'A disruption prevents a critical process from recovering within its approved maximum tolerable period.', category:'operational', scenarioType:'asset_based', riskSource:'Operational disruption', threatEvent:'Loss of people, premises, technology, or key dependency', vulnerability:'Untested recovery arrangements or single points of failure', predisposingCondition:'Critical services have time-sensitive recovery requirements', suggestedOwner:'Operations Office', suggestedCiaImpacts:['Availability','Integrity'], commonCauses:['Site outage','Technology failure','Key-person dependency'], commonConsequences:['Service backlog','Customer harm','Financial and reputational loss'], suggestedInherentLikelihood:3, suggestedInherentImpact:5, suggestedControls:['Business impact analysis','Continuity plan','Recovery exercise'], suggestedEvidence:['Approved BIA','Exercise report','Recovery action log'], relatedFrameworks:['ISO 27005','NIST SP 800-30'], relatedControlIds:[], treatmentSuggestions:['Mitigate','Transfer'], monitoringIndicators:['Recovery exercises overdue','Open continuity actions'], tags:['operational','continuity','resilience'], status:'active' },
  { title:'Strategic transformation does not deliver intended outcomes', description:'A material change programme fails to deliver expected benefits, control readiness, or sustainable adoption.', category:'strategic', scenarioType:'event_based', riskSource:'Strategic execution', threatEvent:'Transformation delay, failure, or uncontrolled change', vulnerability:'Weak governance, dependency management, or benefit ownership', predisposingCondition:'Material outcomes depend on coordinated organisational change', suggestedOwner:'Executive Office', suggestedCiaImpacts:['Integrity','Availability'], commonCauses:['Unclear accountability','Resource constraint','Unmanaged dependency'], commonConsequences:['Benefits shortfall','Control gaps','Cost overrun'], suggestedInherentLikelihood:3, suggestedInherentImpact:4, suggestedControls:['Programme governance','Stage-gate assurance','Benefits tracking'], suggestedEvidence:['Steering committee minutes','Assurance review','Benefits report'], relatedFrameworks:['ISO 27005','NIST SP 800-30'], relatedControlIds:[], treatmentSuggestions:['Mitigate','Accept'], monitoringIndicators:['Milestones missed','Benefits below plan','High-severity programme issues'], tags:['strategic','transformation'], status:'active' },
];
function map(row: any) { return { id:row.id,workspaceId:row.workspace_id,libraryRiskId:row.library_risk_id,title:row.title,description:row.description,category:row.category,scenarioType:row.scenario_type,riskSource:row.risk_source,threatEvent:row.threat_event,vulnerability:row.vulnerability,predisposingCondition:row.predisposing_condition,suggestedOwner:row.suggested_owner,suggestedCiaImpacts:row.suggested_cia_impacts||[],commonCauses:row.common_causes||[],commonConsequences:row.common_consequences||[],suggestedInherentLikelihood:row.suggested_inherent_likelihood,suggestedInherentImpact:row.suggested_inherent_impact,likelihoodRationale:row.likelihood_rationale,impactRationale:row.impact_rationale,suggestedControls:row.suggested_controls||[],suggestedEvidence:row.suggested_evidence||[],relatedFrameworks:row.related_frameworks||[],relatedControlIds:row.related_control_ids||[],treatmentSuggestions:row.treatment_suggestions||[],monitoringIndicators:row.monitoring_indicators||[],tags:row.tags||[],status:row.status,usageCount:Number(row.usage_count||0),createdAt:row.created_at,updatedAt:row.updated_at }; }
export async function ensureRiskLibrarySchema() {
  await query(`CREATE TABLE IF NOT EXISTS risk_library_templates (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,library_risk_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',category TEXT NOT NULL,scenario_type TEXT NOT NULL DEFAULT 'event_based',risk_source TEXT,threat_event TEXT,vulnerability TEXT,predisposing_condition TEXT,suggested_owner TEXT,suggested_cia_impacts JSONB NOT NULL DEFAULT '[]'::jsonb,common_causes JSONB NOT NULL DEFAULT '[]'::jsonb,common_consequences JSONB NOT NULL DEFAULT '[]'::jsonb,suggested_inherent_likelihood INTEGER,suggested_inherent_impact INTEGER,likelihood_rationale TEXT,impact_rationale TEXT,suggested_controls JSONB NOT NULL DEFAULT '[]'::jsonb,suggested_evidence JSONB NOT NULL DEFAULT '[]'::jsonb,related_frameworks JSONB NOT NULL DEFAULT '[]'::jsonb,related_control_ids JSONB NOT NULL DEFAULT '[]'::jsonb,treatment_suggestions JSONB NOT NULL DEFAULT '[]'::jsonb,monitoring_indicators JSONB NOT NULL DEFAULT '[]'::jsonb,tags JSONB NOT NULL DEFAULT '[]'::jsonb,status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','archived')),usage_count INTEGER NOT NULL DEFAULT 0 CHECK (usage_count >= 0),created_by TEXT NOT NULL,updated_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(workspace_id,library_risk_id))`);
  await query(`ALTER TABLE risk_library_templates ADD COLUMN IF NOT EXISTS scenario_type TEXT NOT NULL DEFAULT 'event_based', ADD COLUMN IF NOT EXISTS risk_source TEXT, ADD COLUMN IF NOT EXISTS threat_event TEXT, ADD COLUMN IF NOT EXISTS vulnerability TEXT, ADD COLUMN IF NOT EXISTS predisposing_condition TEXT, ADD COLUMN IF NOT EXISTS likelihood_rationale TEXT, ADD COLUMN IF NOT EXISTS impact_rationale TEXT, ADD COLUMN IF NOT EXISTS monitoring_indicators JSONB NOT NULL DEFAULT '[]'::jsonb`);
  await query(`CREATE INDEX IF NOT EXISTS idx_risk_library_workspace_status ON risk_library_templates (workspace_id,status,updated_at DESC)`);
  await query(`ALTER TABLE risks ADD COLUMN IF NOT EXISTS library_risk_id TEXT`);
}
export async function seedRiskLibraryDefaults(workspaceId:string,actor='system:risk-library'){
  const existing=await query(`SELECT COUNT(*)::int AS count FROM risk_library_templates WHERE workspace_id=$1`,[workspaceId]);
  if(Number(existing.rows[0]?.count||0)>0)return;
  for(const template of DEFAULT_LIBRARY_TEMPLATES) await create(workspaceId,actor,template);
}
export async function list(workspaceId:string,filters:{search?:string;status?:string;category?:string}={}){const conditions=['workspace_id=$1'],values:any[]=[workspaceId];if(filters.status){values.push(filters.status);conditions.push(`status=$${values.length}`);}if(filters.category){values.push(filters.category);conditions.push(`category=$${values.length}`);}if(filters.search){values.push(`%${filters.search}%`);conditions.push(`(library_risk_id ILIKE $${values.length} OR title ILIKE $${values.length} OR description ILIKE $${values.length} OR tags::text ILIKE $${values.length})`);}const r=await query(`SELECT * FROM risk_library_templates WHERE ${conditions.join(' AND ')} ORDER BY updated_at DESC`,values);return r.rows.map(map);}
export async function get(workspaceId:string,id:string){const r=await query(`SELECT * FROM risk_library_templates WHERE workspace_id=$1 AND id=$2`,[workspaceId,id]);return r.rows[0]?map(r.rows[0]):null;}
async function nextReference(workspaceId:string){const r=await query(`SELECT COALESCE(MAX(NULLIF(regexp_replace(library_risk_id,'\\D','','g'),'')::int),0)+1 AS next FROM risk_library_templates WHERE workspace_id=$1`,[workspaceId]);return `LIB-RSK-${String(r.rows[0].next).padStart(3,'0')}`;}
export async function create(workspaceId:string,actor:string,input:RiskLibraryTemplateInput){for(let attempt=0;attempt<5;attempt++){const id=randomUUID(),ref=await nextReference(workspaceId);try{const r=await query(`INSERT INTO risk_library_templates (id,workspace_id,library_risk_id,title,description,category,scenario_type,risk_source,threat_event,vulnerability,predisposing_condition,suggested_owner,suggested_cia_impacts,common_causes,common_consequences,suggested_inherent_likelihood,suggested_inherent_impact,likelihood_rationale,impact_rationale,suggested_controls,suggested_evidence,related_frameworks,related_control_ids,treatment_suggestions,monitoring_indicators,tags,status,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb,$15::jsonb,$16,$17,$18,$19,$20::jsonb,$21::jsonb,$22::jsonb,$23::jsonb,$24::jsonb,$25::jsonb,$26::jsonb,$27,$28,$28) RETURNING *`,[id,workspaceId,ref,input.title,input.description||'',input.category,input.scenarioType||'event_based',input.riskSource||null,input.threatEvent||null,input.vulnerability||null,input.predisposingCondition||null,input.suggestedOwner||null,JSON.stringify(input.suggestedCiaImpacts||[]),JSON.stringify(input.commonCauses||[]),JSON.stringify(input.commonConsequences||[]),input.suggestedInherentLikelihood??null,input.suggestedInherentImpact??null,input.likelihoodRationale||null,input.impactRationale||null,JSON.stringify(input.suggestedControls||[]),JSON.stringify(input.suggestedEvidence||[]),JSON.stringify(input.relatedFrameworks||[]),JSON.stringify(input.relatedControlIds||[]),JSON.stringify(input.treatmentSuggestions||[]),JSON.stringify(input.monitoringIndicators||[]),JSON.stringify(input.tags||[]),input.status||'draft',actor]);return map(r.rows[0]);}catch(error:any){if(error?.code!=='23505'||attempt===4)throw error;}}throw new Error('Unable to allocate a unique Risk Library reference');}
export async function update(workspaceId:string,id:string,actor:string,input:Partial<RiskLibraryTemplateInput>){const columns:Record<string,string>={title:'title',description:'description',category:'category',scenarioType:'scenario_type',riskSource:'risk_source',threatEvent:'threat_event',vulnerability:'vulnerability',predisposingCondition:'predisposing_condition',suggestedOwner:'suggested_owner',suggestedCiaImpacts:'suggested_cia_impacts',commonCauses:'common_causes',commonConsequences:'common_consequences',suggestedInherentLikelihood:'suggested_inherent_likelihood',suggestedInherentImpact:'suggested_inherent_impact',likelihoodRationale:'likelihood_rationale',impactRationale:'impact_rationale',suggestedControls:'suggested_controls',suggestedEvidence:'suggested_evidence',relatedFrameworks:'related_frameworks',relatedControlIds:'related_control_ids',treatmentSuggestions:'treatment_suggestions',monitoringIndicators:'monitoring_indicators',tags:'tags',status:'status'};const sets:string[]=[],values:any[]=[workspaceId,id];let p=3;for(const [key,column] of Object.entries(columns)){const value=input[key as keyof typeof input];if(value!==undefined){sets.push(`${column}=$${p++}${jsonColumns.has(column)?'::jsonb':''}`);values.push(jsonColumns.has(column)?JSON.stringify(value):value);}}if(!sets.length)return get(workspaceId,id);sets.push(`updated_by=$${p++}`,`updated_at=NOW()`);values.push(actor);const r=await query(`UPDATE risk_library_templates SET ${sets.join(',')} WHERE workspace_id=$1 AND id=$2 RETURNING *`,values);return r.rows[0]?map(r.rows[0]):null;}
export async function recordUse(workspaceId:string,id:string){const r=await query(`UPDATE risk_library_templates SET usage_count=usage_count+1,updated_at=NOW() WHERE workspace_id=$1 AND id=$2 RETURNING *`,[workspaceId,id]);return r.rows[0]?map(r.rows[0]):null;}
