import { randomUUID } from 'node:crypto';
import { query } from '../db.js';

export type RiskLibraryStatus = 'draft' | 'active' | 'archived';
export interface RiskLibraryTemplateInput {
  title: string; description?: string; category: string; suggestedOwner?: string | null;
  scenarioType?: 'event_based' | 'asset_based'; riskSource?: string | null; threatEvent?: string | null;
  vulnerability?: string | null; predisposingCondition?: string | null;
  suggestedCiaImpacts?: string[]; commonCauses?: string[]; commonConsequences?: string[];
  suggestedInherentLikelihood?: number | null; suggestedInherentImpact?: number | null;
  likelihoodRationale?: string | null; impactRationale?: string | null;
  suggestedControls?: string[]; suggestedEvidence?: string[]; relatedFrameworks?: string[];
  relatedControlIds?: string[]; treatmentSuggestions?: string[]; monitoringIndicators?: string[];
  tags?: string[]; status?: RiskLibraryStatus;
}
const jsonColumns = new Set(['suggested_cia_impacts','common_causes','common_consequences','suggested_controls','suggested_evidence','related_frameworks','related_control_ids','treatment_suggestions','monitoring_indicators','tags']);
function map(row: any) { return { id:row.id,workspaceId:row.workspace_id,libraryRiskId:row.library_risk_id,title:row.title,description:row.description,category:row.category,scenarioType:row.scenario_type,riskSource:row.risk_source,threatEvent:row.threat_event,vulnerability:row.vulnerability,predisposingCondition:row.predisposing_condition,suggestedOwner:row.suggested_owner,suggestedCiaImpacts:row.suggested_cia_impacts||[],commonCauses:row.common_causes||[],commonConsequences:row.common_consequences||[],suggestedInherentLikelihood:row.suggested_inherent_likelihood,suggestedInherentImpact:row.suggested_inherent_impact,likelihoodRationale:row.likelihood_rationale,impactRationale:row.impact_rationale,suggestedControls:row.suggested_controls||[],suggestedEvidence:row.suggested_evidence||[],relatedFrameworks:row.related_frameworks||[],relatedControlIds:row.related_control_ids||[],treatmentSuggestions:row.treatment_suggestions||[],monitoringIndicators:row.monitoring_indicators||[],tags:row.tags||[],status:row.status,usageCount:Number(row.usage_count||0),createdAt:row.created_at,updatedAt:row.updated_at }; }
export async function ensureRiskLibrarySchema() {
  await query(`CREATE TABLE IF NOT EXISTS risk_library_templates (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,library_risk_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',category TEXT NOT NULL,scenario_type TEXT NOT NULL DEFAULT 'event_based',risk_source TEXT,threat_event TEXT,vulnerability TEXT,predisposing_condition TEXT,suggested_owner TEXT,suggested_cia_impacts JSONB NOT NULL DEFAULT '[]'::jsonb,common_causes JSONB NOT NULL DEFAULT '[]'::jsonb,common_consequences JSONB NOT NULL DEFAULT '[]'::jsonb,suggested_inherent_likelihood INTEGER,suggested_inherent_impact INTEGER,likelihood_rationale TEXT,impact_rationale TEXT,suggested_controls JSONB NOT NULL DEFAULT '[]'::jsonb,suggested_evidence JSONB NOT NULL DEFAULT '[]'::jsonb,related_frameworks JSONB NOT NULL DEFAULT '[]'::jsonb,related_control_ids JSONB NOT NULL DEFAULT '[]'::jsonb,treatment_suggestions JSONB NOT NULL DEFAULT '[]'::jsonb,monitoring_indicators JSONB NOT NULL DEFAULT '[]'::jsonb,tags JSONB NOT NULL DEFAULT '[]'::jsonb,status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','archived')),usage_count INTEGER NOT NULL DEFAULT 0 CHECK (usage_count >= 0),created_by TEXT NOT NULL,updated_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(workspace_id,library_risk_id))`);
  await query(`ALTER TABLE risk_library_templates ADD COLUMN IF NOT EXISTS scenario_type TEXT NOT NULL DEFAULT 'event_based', ADD COLUMN IF NOT EXISTS risk_source TEXT, ADD COLUMN IF NOT EXISTS threat_event TEXT, ADD COLUMN IF NOT EXISTS vulnerability TEXT, ADD COLUMN IF NOT EXISTS predisposing_condition TEXT, ADD COLUMN IF NOT EXISTS likelihood_rationale TEXT, ADD COLUMN IF NOT EXISTS impact_rationale TEXT, ADD COLUMN IF NOT EXISTS monitoring_indicators JSONB NOT NULL DEFAULT '[]'::jsonb`);
  await query(`CREATE INDEX IF NOT EXISTS idx_risk_library_workspace_status ON risk_library_templates (workspace_id,status,updated_at DESC)`);
  await query(`ALTER TABLE risks ADD COLUMN IF NOT EXISTS library_risk_id TEXT`);
}
export async function list(workspaceId:string,filters:{search?:string;status?:string;category?:string}={}){const conditions=['workspace_id=$1'],values:any[]=[workspaceId];if(filters.status){values.push(filters.status);conditions.push(`status=$${values.length}`);}if(filters.category){values.push(filters.category);conditions.push(`category=$${values.length}`);}if(filters.search){values.push(`%${filters.search}%`);conditions.push(`(library_risk_id ILIKE $${values.length} OR title ILIKE $${values.length} OR description ILIKE $${values.length} OR tags::text ILIKE $${values.length})`);}const r=await query(`SELECT * FROM risk_library_templates WHERE ${conditions.join(' AND ')} ORDER BY updated_at DESC`,values);return r.rows.map(map);}
export async function get(workspaceId:string,id:string){const r=await query(`SELECT * FROM risk_library_templates WHERE workspace_id=$1 AND id=$2`,[workspaceId,id]);return r.rows[0]?map(r.rows[0]):null;}
async function nextReference(workspaceId:string){const r=await query(`SELECT COALESCE(MAX(NULLIF(regexp_replace(library_risk_id,'\\D','','g'),'')::int),0)+1 AS next FROM risk_library_templates WHERE workspace_id=$1`,[workspaceId]);return `LIB-RSK-${String(r.rows[0].next).padStart(3,'0')}`;}
export async function create(workspaceId:string,actor:string,input:RiskLibraryTemplateInput){for(let attempt=0;attempt<5;attempt++){const id=randomUUID(),ref=await nextReference(workspaceId);try{const r=await query(`INSERT INTO risk_library_templates (id,workspace_id,library_risk_id,title,description,category,scenario_type,risk_source,threat_event,vulnerability,predisposing_condition,suggested_owner,suggested_cia_impacts,common_causes,common_consequences,suggested_inherent_likelihood,suggested_inherent_impact,likelihood_rationale,impact_rationale,suggested_controls,suggested_evidence,related_frameworks,related_control_ids,treatment_suggestions,monitoring_indicators,tags,status,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb,$15::jsonb,$16,$17,$18,$19,$20::jsonb,$21::jsonb,$22::jsonb,$23::jsonb,$24::jsonb,$25::jsonb,$26::jsonb,$27,$28,$28) RETURNING *`,[id,workspaceId,ref,input.title,input.description||'',input.category,input.scenarioType||'event_based',input.riskSource||null,input.threatEvent||null,input.vulnerability||null,input.predisposingCondition||null,input.suggestedOwner||null,JSON.stringify(input.suggestedCiaImpacts||[]),JSON.stringify(input.commonCauses||[]),JSON.stringify(input.commonConsequences||[]),input.suggestedInherentLikelihood??null,input.suggestedInherentImpact??null,input.likelihoodRationale||null,input.impactRationale||null,JSON.stringify(input.suggestedControls||[]),JSON.stringify(input.suggestedEvidence||[]),JSON.stringify(input.relatedFrameworks||[]),JSON.stringify(input.relatedControlIds||[]),JSON.stringify(input.treatmentSuggestions||[]),JSON.stringify(input.monitoringIndicators||[]),JSON.stringify(input.tags||[]),input.status||'draft',actor]);return map(r.rows[0]);}catch(error:any){if(error?.code!=='23505'||attempt===4)throw error;}}throw new Error('Unable to allocate a unique Risk Library reference');}
export async function update(workspaceId:string,id:string,actor:string,input:Partial<RiskLibraryTemplateInput>){const columns:Record<string,string>={title:'title',description:'description',category:'category',scenarioType:'scenario_type',riskSource:'risk_source',threatEvent:'threat_event',vulnerability:'vulnerability',predisposingCondition:'predisposing_condition',suggestedOwner:'suggested_owner',suggestedCiaImpacts:'suggested_cia_impacts',commonCauses:'common_causes',commonConsequences:'common_consequences',suggestedInherentLikelihood:'suggested_inherent_likelihood',suggestedInherentImpact:'suggested_inherent_impact',likelihoodRationale:'likelihood_rationale',impactRationale:'impact_rationale',suggestedControls:'suggested_controls',suggestedEvidence:'suggested_evidence',relatedFrameworks:'related_frameworks',relatedControlIds:'related_control_ids',treatmentSuggestions:'treatment_suggestions',monitoringIndicators:'monitoring_indicators',tags:'tags',status:'status'};const sets:string[]=[],values:any[]=[workspaceId,id];let p=3;for(const [key,column] of Object.entries(columns)){const value=input[key as keyof typeof input];if(value!==undefined){sets.push(`${column}=$${p++}${jsonColumns.has(column)?'::jsonb':''}`);values.push(jsonColumns.has(column)?JSON.stringify(value):value);}}if(!sets.length)return get(workspaceId,id);sets.push(`updated_by=$${p++}`,`updated_at=NOW()`);values.push(actor);const r=await query(`UPDATE risk_library_templates SET ${sets.join(',')} WHERE workspace_id=$1 AND id=$2 RETURNING *`,values);return r.rows[0]?map(r.rows[0]):null;}
export async function recordUse(workspaceId:string,id:string){const r=await query(`UPDATE risk_library_templates SET usage_count=usage_count+1,updated_at=NOW() WHERE workspace_id=$1 AND id=$2 RETURNING *`,[workspaceId,id]);return r.rows[0]?map(r.rows[0]):null;}
