export const theme = {
  colors: {
    primary: 'var(--color-primary)',
    primaryHover: 'var(--color-primary-strong)',
    primaryLight: 'var(--color-primary-soft)',
    accent: 'var(--color-accent)',
    background: 'var(--color-bg)',
    backgroundAlt: 'var(--color-bg-alt)',
    surface: 'var(--color-surface)',
    surfaceHover: 'var(--color-surface-hover)',
    border: 'var(--color-border)',
    borderLight: 'var(--color-border-soft)',
    overlay: 'var(--color-overlay)',
    text: {
      main: 'var(--color-text-main)',
      secondary: 'var(--color-text-secondary)',
      muted: 'var(--color-text-muted)',
      inverse: 'var(--color-text-inverse)',
    },
    semantic: {
      success: 'var(--color-success)',
      successLight: 'var(--color-success-soft)',
      warning: 'var(--color-warning)',
      warningLight: 'var(--color-warning-soft)',
      danger: 'var(--color-danger)',
      dangerLight: 'var(--color-danger-soft)',
      info: 'var(--color-info)',
      infoLight: 'var(--color-info-soft)',
    },
    risk: {
      critical: 'var(--color-danger-strong)',
      criticalBg: 'var(--color-danger-soft)',
      high: 'var(--color-warning-strong)',
      highBg: 'var(--color-warning-soft)',
      medium: 'var(--color-warning)',
      mediumBg: 'var(--color-warning-soft)',
      low: 'var(--color-success-strong)',
      lowBg: 'var(--color-success-soft)',
    },
    heatmap: {
      negligible: 'var(--color-success-strong)',
      low: '#84CC16',
      medium: '#EAB308',
      high: '#F97316',
      critical: 'var(--color-danger)',
    },
    gradients: {
      hero: 'var(--gradient-hero)',
      heroSubtle: 'var(--gradient-hero-subtle)',
      card: 'var(--gradient-card)',
    },
    sidebar: {
      background: 'var(--color-sidebar-bg)',
      itemHover: 'var(--color-sidebar-hover)',
      itemActive: 'var(--color-sidebar-active)',
      border: 'var(--color-sidebar-border)',
    },
  },

  typography: {
    fontFamily: '"Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    sizes: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
    },
    weights: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
  },

  spacing: {
    0: '0',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem',
    16: '4rem',
    20: '5rem',
  },

  borderRadius: {
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    '2xl': '1rem',
    full: '9999px',
  },

  shadows: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    card: 'var(--shadow-card)',
    cardHover: 'var(--shadow-card-hover)',
  },
};

export type Theme = typeof theme;
